#!/usr/bin/env bash
set -euo pipefail

# iptables_setup.sh
#
# 目的：让本机所有 TCP 流量透明转发到 clashlite 的 tproxy 端口。
#
# 注意：
# - 这是“本机模式”（OUTPUT 链）。如果你要做网关，需要 PREROUTING。
# - 一定要绕过 clashlite 自己的进程（按 uid），否则会回环。
#
# 用法：
#   sudo bash scripts/iptables_setup.sh --tproxy-port 12345 --dns-port 1053 --bypass-uid 1000

TPROXY_PORT=12345
DNS_PORT=1053
BYPASS_UID=""
CHAIN=CLASHLITE

while [[ $# -gt 0 ]]; do
  case "$1" in
    --tproxy-port) TPROXY_PORT="$2"; shift 2;;
    --dns-port) DNS_PORT="$2"; shift 2;;
    --bypass-uid) BYPASS_UID="$2"; shift 2;;
    *) echo "Unknown arg: $1"; exit 2;;
  esac
done

if [[ -z "$BYPASS_UID" ]]; then
  echo "ERROR: --bypass-uid is required (use a dedicated user or your current uid)" >&2
  exit 2
fi

# create chain if not exists
iptables -t nat -N "$CHAIN" 2>/dev/null || true

# flush chain
iptables -t nat -F "$CHAIN"

# 1) bypass local
iptables -t nat -A "$CHAIN" -d 127.0.0.0/8 -j RETURN

# 2) bypass DNS to avoid loop (if local resolver uses our FakeDNS)
iptables -t nat -A "$CHAIN" -p udp --dport "$DNS_PORT" -j RETURN

# 3) bypass traffic generated by the bypass uid (clashlite itself)
iptables -t nat -A "$CHAIN" -m owner --uid-owner "$BYPASS_UID" -j RETURN

# 4) redirect TCP to local port
iptables -t nat -A "$CHAIN" -p tcp -j REDIRECT --to-ports "$TPROXY_PORT"

# hook chain into OUTPUT (idempotent)
iptables -t nat -C OUTPUT -p tcp -j "$CHAIN" 2>/dev/null || iptables -t nat -A OUTPUT -p tcp -j "$CHAIN"

echo "[OK] iptables rules installed (OUTPUT tcp -> REDIRECT $TPROXY_PORT), bypass uid=$BYPASS_UID"

echo "Next step: point your system DNS to 127.0.0.1:$DNS_PORT (FakeDNS)."
